project: "results"
static-files:
  diamond-db: "/mnt/nfs/bioinfdata/data_other/db/blast/nr/20190322/nr-diamond-0.9.24.dmnd"
  kaiju-db: "/mnt/nfs/bioinfdata/home/NIOO/thomg/db/kaiju/"
  mmseqs-db: "/mnt/nfs/bioinfdata/home/NIOO/thomg/db/swissprot/uprot_sp_mmseqs"
min-contig-length: 10000
parts-enabled:
  qc: false
  krona: false
  diamond: false
  quast: true
  checkm: false
  mmseqs: false
